title: SLASHED
description: A modern, layered CSS framework built on @layer
url: "https://slashed.codeslash.dev"

plugins:
  - jekyll-optional-front-matter

exclude:
  - node_modules
  - configurator
  - configurator-archive
  - core
  - optional
  - scripts
  - tests
  - dist
  - analysis
  - demos/generate.mjs
  - demos/validate.mjs
  - demos/.validate
  - bundle.config.json
  - commitlint.config.js
  - playwright.config.js
  - ".stylelintrc.json"
  - ".release-it.json"
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock

defaults:
  - scope:
      path: "docs"
    values:
      layout: default
      render_with_liquid: false
  - scope:
      path: ""
    values:
      layout: default
