/**
 * Documentation artifact sync regression.
 *
 * These checks cover static HTML/report artifacts that are not regenerated by
 * the main docs pipeline but are still presented as framework/API coverage.
 * They must not mention live tokens that have been removed from docs/api-index.
 *
 * Run: node --test tests/docs-artifacts-sync.test.js
 */
import { describe, test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const API_INDEX_PATH = path.join(ROOT, 'docs', 'api-index.json');
const TOKEN_REFERENCE_HTML = path.join(ROOT, 'docs', 'test-coverage-6-token-reference.html');
const TOKENS_REPORT_PATH = path.join(ROOT, 'reports', 'full-api-audit', 'results', 'tokens-report.json');
const REACHABLE_UI_PATH = path.join(ROOT, 'reports', 'full-api-audit', 'results', 'reachable-ui.json');

const apiTokens = JSON.parse(fs.readFileSync(API_INDEX_PATH, 'utf8'))
  .entries
  .filter(e => e.type === 'token')
  .map(e => e.name);

const apiTokenSet = new Set(apiTokens);

function unknownTokens(names) {
  return [...new Set(names.filter(name => !apiTokenSet.has(name)))].sort();
}

describe('static documentation artifacts stay aligned to docs/api-index.json', () => {
  test('token reference coverage page embeds exactly the current API token list', () => {
    const html = fs.readFileSync(TOKEN_REFERENCE_HTML, 'utf8');
    const match = html.match(/var TOKENS = (\[[^\n]+]);/);

    assert.ok(match, 'docs/test-coverage-6-token-reference.html must embed var TOKENS = [...]');
    assert.deepEqual(JSON.parse(match[1]).sort(), [...apiTokens].sort());
  });

  test('full API audit token report does not retain removed token rows', () => {
    const report = JSON.parse(fs.readFileSync(TOKENS_REPORT_PATH, 'utf8'));
    const rowNames = report.rows.map(row => row.name);

    assert.equal(report.summary.totalTokens, apiTokens.length);
    assert.equal(report.rows.length, apiTokens.length);
    assert.deepEqual(unknownTokens(rowNames), []);
  });

  test('full API audit reachable UI list does not retain removed tokens', () => {
    const reachable = JSON.parse(fs.readFileSync(REACHABLE_UI_PATH, 'utf8'));

    assert.deepEqual(unknownTokens(reachable), []);
  });
});
